## Exercise 1: NumPy: Create an array with values ranging from 12 to 38

In [16]:
import numpy as np
arr = np.arange(12,39)
arr

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37, 38])

## Exercise 2: Add a border around an existing array
##### Hint: np.pad()

In [25]:
arr = [[1,1,1],[1,1,1],[1,1,1]]
arr

[[1, 1, 1], [1, 1, 1], [1, 1, 1]]

In [62]:
arr = np.ones((3,3))
def pad_with(vector, pad_width, iaxis, kwargs):
    pad_value = kwargs.get('padder', 55)
    vector[:pad_width[0]] = pad_value
    vector[-pad_width[1]:] = pad_value
#np.pad(arr, 1, pad_with)
np.pad(arr, 1, pad_with, padder=0)

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

## Exercise 3: Convert a list and tuple into arrays

In [78]:
lst = [1, 2, 3, 4, 5, 6, 7, 8]
l = np.array(lst)
l

numpy.ndarray

In [80]:
a = np.array([8,4,6,1,2,3])
b = a.reshape(2,3)
b

array([[8, 4, 6],
       [1, 2, 3]])

In [81]:
 np.asarray(b)

array([[8, 4, 6],
       [1, 2, 3]])

## Also try np.asarray for the problem above! 

## Exercise 4:  Convert the values of Centigrade degrees into Fahrenheit degrees

In [94]:
f =[0.,   12.,   45.21, 34.,   99.91]
f = np.array(f)
c = (5*(f-32))/9
print('deg in celsius : ' ,c)

deg in celsius :  [-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]


## Exercise 5: Write a NumPy program to find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements. 

In [77]:
arr = np.array([1,2,3])
print ('number of elements of an array :', arr.size)
print ('length of one array element in bytes: ', arr.itemsize)
print ('total bytes consumed by the elements: ', arr.size * arr.itemsize)

number of elements of an array : 3
length of one array element in bytes:  4
total bytes consumed by the elements:  12


## Exercise 6: Get the unique elements of an array

In [97]:
arr = [10, 10, 20, 20, 30, 30]
np.unique(arr)
arr1 = [[1,1],[2,3]]
np.unique(arr1)

array([1, 2, 3])

## Exercise 7: Change the dimension of an array


In [101]:
arr = np.arange(1,10,1)
arr.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Exercise 8: Create a 1-D array of 30 evenly spaced elements between 2.5. and 6.5, inclusive

In [103]:
np.linspace(2.5,6.5,30)

array([2.5       , 2.63793103, 2.77586207, 2.9137931 , 3.05172414,
       3.18965517, 3.32758621, 3.46551724, 3.60344828, 3.74137931,
       3.87931034, 4.01724138, 4.15517241, 4.29310345, 4.43103448,
       4.56896552, 4.70689655, 4.84482759, 4.98275862, 5.12068966,
       5.25862069, 5.39655172, 5.53448276, 5.67241379, 5.81034483,
       5.94827586, 6.0862069 , 6.22413793, 6.36206897, 6.5       ])

## Exercise 9: Convert 1-D arrays as columns into a 2-D array

In [127]:
arr1=np.array([10,20,30])
arr2 = np.array([40,50,60])
np.stack((arr1,arr2), axis=1)


array([[10, 40],
       [20, 50],
       [30, 60]])

## Exercise 10: Create a 5x5 matrix with row values ranging from 0 to 4

In [167]:
a = np.zeros((5,5))
a = a + np.arange(5)
a

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

## Exercise 11: Sum of all the multiples of 3 or 5 below 100

In [156]:
arr = np.arange(1,100)
a = arr[(arr%3==0) | (arr%5==0)]
a.sum()

2318

## Exercise 12: Combine a one and a two dimensional array together and display their elements
##### Hint : np.nditer()

In [176]:
x = np.arange(4)
y = np.arange(4)
for a, b in np.nditer([x,y]):
    print(a)
    print(b)

0
0
1
1
2
2
3
3


In [185]:
x = np.arange(4)
y = np.arange(8).reshape(2,4)
for a,b in np.nditer([x,y]):
    print(a,':',b,sep='')

0:0
1:1
2:2
3:3
0:4
1:5
2:6
3:7


## Exercise 13: Write a NumPy program to replace all elements of NumPy array that are greater than specified array.

In [228]:
arr = np.array([[0.42436315, 0.48558583, 0.32924763],
 [0.7439979,  0.58220701, 0.38213418],
 [0.5097581,  0.34528799, 0.1563123 ]])
shape = arr.shape
for x in range(0,shape[0]):
    for y in range(0,shape[1]):
        if arr[x, y] >= 0.5:
            arr[x, y] = 0.5
print(arr)

[[0.42436315 0.48558583 0.32924763]
 [0.5        0.5        0.38213418]
 [0.5        0.34528799 0.1563123 ]]


In [230]:
arr = np.array([[0.42436315, 0.48558583, 0.32924763],
 [0.7439979,  0.58220701, 0.38213418],
 [0.5097581,  0.34528799, 0.1563123 ]])
arr[arr > 0.5 ] = 0.5
arr

array([[0.42436315, 0.48558583, 0.32924763],
       [0.5       , 0.5       , 0.38213418],
       [0.5       , 0.34528799, 0.1563123 ]])

## Exercise 14: Add a new row to an empty numpy array

In [10]:
# without using numpy
arr = []
arr1 = [[10, 20, 30],[40,50,60]]
arr + arr1

[[10, 20, 30], [40, 50, 60]]

In [39]:
#using numpy
arr = np.empty((0,3), int)
arr = np.append(arr, np.array([[10,20,30]]), axis =0)
arr = np.append(arr, np.array([[20,30,40]]), axis =0)
arr

array([[10, 20, 30],
       [20, 30, 40]])

## Exercise 15: Write a NumPy program to join a sequence of arrays along a new axis. 

In [6]:
arr = [[1,2,3],[2,3,4]]
arr

[[1, 2, 3], [2, 3, 4]]

In [41]:
np.array([[1,2,3],[2,3,4]])

array([[1, 2, 3],
       [2, 3, 4]])

In [50]:
arr1 = np.array([1,2,3])
arr2 = np.array([2,3,4])
np.vstack((arr1,arr2))

array([[1, 2, 3],
       [2, 3, 4]])

In [69]:
a = np.array([[1], [2], [3]])
b = np.array([[2], [3], [4]])
print(a)
print()
print(b)
print()
print(np.hstack((a , b)))

[[1]
 [2]
 [3]]

[[2]
 [3]
 [4]]

[[1 2]
 [2 3]
 [3 4]]
