In [198]:
'''
Install
pip - package installer for python
!pip install numpy
!conda install numpy
'''

'\nInstall\npip - package installer for python\n!pip install numpy\n!conda install numpy\n'

In [199]:
!pip install numpy

In [200]:
import numpy as n
arr = n.array([1,2,3])

In [201]:
print(arr)

[1 2 3]


In [202]:
import numpy as np
arr = np.array([2,3,4,5,6,3])
print(arr)
arr

[2 3 4 5 6 3]


array([2, 3, 4, 5, 6, 3])

In [203]:
type(arr)

numpy.ndarray

In [204]:
type(arr[0])

numpy.int32

In [205]:
arr = np.array([3,2,4,2,'jay'])

type(arr[0])

numpy.str_

In [206]:
np.__version__

'1.19.2'

In [207]:
arr_2d = np.array([[1,2,3],[4,5,6]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [208]:
arr_2d.shape

(2, 3)

In [209]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_2d.shape

(3, 3)

In [210]:
#Functions involved in creating an array

In [211]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])

In [212]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [213]:
a.reshape(3,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [214]:
#Linspace: This function creates elements which are equally spaced from each other
#(start, stop, count of elements it will generate from starting and ending included)

In [215]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [216]:
np.linspace(10,100,10)

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [217]:
lst = [0,1,2,3,4,5,6,7,8]
lst[1:]

[1, 2, 3, 4, 5, 6, 7, 8]

In [218]:
#list slicing to remove first element
np.linspace(10,100,10)[1:]

array([ 20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [219]:
np.linspace(10,100,10)

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [220]:
np.linspace(10,100,10,endpoint=False)

array([10., 19., 28., 37., 46., 55., 64., 73., 82., 91.])

In [221]:
#Arange
#Generates values based on the step you specify
np.arange(0, 100, 10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [222]:
#square matrix - num of rows is equal to num of cols
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [223]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [224]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [225]:
np.zeros((4,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [226]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [227]:
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [228]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [229]:
lst = [0,1,2,3,4,5]
lst[::-1]

[5, 4, 3, 2, 1, 0]

In [230]:
np.eye(3)[::-1]

array([[0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [231]:
A=[[1,2,3],
   [4,5,6],
   [7,8,9]]
A[2][2]

9

In [273]:
arr = np.eye(6, dtype=int)
arr

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]])

In [233]:
arr[::-1]

array([[0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0]])

In [234]:
A=np.array([[1,2,3],
   [4,5,6],
   [7,8,9]])
A[2][1]


8

In [235]:
A.diagonal()

array([1, 5, 9])

In [236]:
A.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [237]:
np.fliplr(A).diagonal()

array([3, 5, 7])

## np.eye?

In [238]:
np.zeros?

Docstring:
zeros(shape, dtype=float, order='C')

Return a new array of given shape and type, filled with zeros.

Parameters
----------
shape : int or tuple of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    The desired data-type for the array, e.g., `numpy.int8`.  Default is
    `numpy.float64`.
order : {'C', 'F'}, optional, default: 'C'
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in
    memory.

Returns
-------
out : ndarray
    Array of zeros with the given shape, dtype, and order.

See Also
--------
zeros_like : Return an array of zeros with shape and type of input.
empty : Return a new uninitialized array.
ones : Return a new array setting values to one.
full : Return a new array of given shape filled with value.

Examples
--------
>>> np.zeros(5)
array([ 0.,  0.,  0.,  0.,  0.])

>>> np.zeros((5,), dtype=int)
array([0, 0, 0, 0, 0])

>>> np.zeros((2, 1))
array([[ 0.],
      

In [239]:
import numpy
numpy.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [240]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [241]:
#operations with numpy array
arr = np.array([20,30,40])
dup = arr.copy()
dup

array([20, 30, 40])

In [242]:
arr[0] = 60
dup

array([20, 30, 40])

In [243]:
arr

array([60, 30, 40])

In [244]:
dup = arr.view()
dup

array([60, 30, 40])

In [245]:
for i in arr:
    print(i)

60
30
40


In [246]:
arr_2d = ([1,2,3,4],[5,6,7,8])

In [247]:
for i in arr_2d:
    print(i)

[1, 2, 3, 4]
[5, 6, 7, 8]


In [248]:
for i in arr_2d:
    for x in i:
        print(x)

1
2
3
4
5
6
7
8


In [249]:
arr_3d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_3d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [250]:
arr_3d.shape

(3, 3)

In [251]:
arr_3d = np.array([[[[1,2,3],[4,5,6],[7,8,9]]]])
arr_3d.shape

(1, 1, 3, 3)

In [252]:
arr_3d = np.array([[[1,2,3],[4,5,6],[7,8,9],[3,6,8]]])
arr_3d.shape

(1, 4, 3)

In [253]:
arr_3d = np.array([[[1,2,3],[4,5,6],[7,8,9],[3,6,8]],[[11,12,13],[14,15,16],[17,18,19],[13,16,18]]])
arr_3d.shape

(2, 4, 3)

In [254]:
for room in arr_3d:
    print('Inside the room', room)
    for each_row in room:
        print('Inside room: {} row'.format(each_row))
        for data_scientist in each_row:
              print(data_scientist)

Inside the room [[1 2 3]
 [4 5 6]
 [7 8 9]
 [3 6 8]]
Inside room: [1 2 3] row
1
2
3
Inside room: [4 5 6] row
4
5
6
Inside room: [7 8 9] row
7
8
9
Inside room: [3 6 8] row
3
6
8
Inside the room [[11 12 13]
 [14 15 16]
 [17 18 19]
 [13 16 18]]
Inside room: [11 12 13] row
11
12
13
Inside room: [14 15 16] row
14
15
16
Inside room: [17 18 19] row
17
18
19
Inside room: [13 16 18] row
13
16
18


In [255]:
'''
for room in range(1,len(arr_3d)+1):
    print('Inside the room', room)
    for each_row in range(1, len(room)):
        print('Inside room: {} row'.format(each_row))
'''

"\nfor room in range(1,len(arr_3d)+1):\n    print('Inside the room', room)\n    for each_row in range(1, len(room)):\n        print('Inside room: {} row'.format(each_row))\n"

In [256]:
len(arr_3d)

2

In [257]:
#Addition, sub, mul in mum aray
arr1 = np.array(range(1,17,1))
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [258]:
arr1 = arr1.reshape(4,4)
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [259]:
arr2 = np.array(range(10,170,10))
arr2 = arr2.reshape(4,4)
arr2

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120],
       [130, 140, 150, 160]])

In [260]:
arr1+arr2

array([[ 11,  22,  33,  44],
       [ 55,  66,  77,  88],
       [ 99, 110, 121, 132],
       [143, 154, 165, 176]])

In [261]:
np.add(arr1,arr2)

array([[ 11,  22,  33,  44],
       [ 55,  66,  77,  88],
       [ 99, 110, 121, 132],
       [143, 154, 165, 176]])

In [262]:
abs(arr1-arr2)

array([[  9,  18,  27,  36],
       [ 45,  54,  63,  72],
       [ 81,  90,  99, 108],
       [117, 126, 135, 144]])

In [263]:
arr1-arr2

array([[  -9,  -18,  -27,  -36],
       [ -45,  -54,  -63,  -72],
       [ -81,  -90,  -99, -108],
       [-117, -126, -135, -144]])

In [264]:
np.subtract(arr1,arr2)

array([[  -9,  -18,  -27,  -36],
       [ -45,  -54,  -63,  -72],
       [ -81,  -90,  -99, -108],
       [-117, -126, -135, -144]])

In [265]:
np.subtract(arr2,arr1)

array([[  9,  18,  27,  36],
       [ 45,  54,  63,  72],
       [ 81,  90,  99, 108],
       [117, 126, 135, 144]])

In [123]:
arr1*arr2

array([[  10,   40,   90,  160],
       [ 250,  360,  490,  640],
       [ 810, 1000, 1210, 1440],
       [1690, 1960, 2250, 2560]])

In [276]:
arr2/arr1

array([[10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.]])

In [275]:
np.array(arr2/arr1,dtype=int)

array([[10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.]])

In [125]:
np.multiply(arr1,arr2)

array([[  10,   40,   90,  160],
       [ 250,  360,  490,  640],
       [ 810, 1000, 1210, 1440],
       [1690, 1960, 2250, 2560]])

In [126]:
np.divide(arr1,arr2)

array([[0.1, 0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1, 0.1]])

In [132]:
arr1 = np.array([[1,2],[3,5]])
arr2 = np.array([[2,3],[4,5]])

In [133]:
arr1*arr2

array([[ 2,  6],
       [12, 25]])

In [134]:
arr1.dot(arr2)

array([[10, 13],
       [26, 34]])

In [135]:
np.dot(arr1,arr2)

array([[10, 13],
       [26, 34]])

In [280]:
arr1 = np.array([[2,3,6],[4,5,7]])
arr2 = np.array([[2,5,6],[7,8,7],[9,10,8]])
np.dot(arr1,arr2)

array([[ 79,  94,  81],
       [106, 130, 115]])

In [1]:
arr1 = np.array([[2,3,6],[4,5,7],[1,2,3],[4,7,9]])
arr2 = np.array([[2,5,6],[7,8,7],[9,10,8]])
np.dot(arr1,arr2)
#For a dot product, the col of 1 array should be equal to row of 2nd array
#here, np.dot(arr2,arr1) -> will throw value error

NameError: name 'np' is not defined

In [287]:
#join numpy arrays
arr1 = np.array([2,3,6])
arr2 = np.array([5,6,7])

In [294]:
np.stack?

Signature: np.stack(arrays, axis=0, out=None)
Docstring:
Join a sequence of arrays along a new axis.

The ``axis`` parameter specifies the index of the new axis in the
dimensions of the result. For example, if ``axis=0`` it will be the first
dimension and if ``axis=-1`` it will be the last dimension.

.. versionadded:: 1.10.0

Parameters
----------
arrays : sequence of array_like
    Each array must have the same shape.

axis : int, optional
    The axis in the result array along which the input arrays are stacked.

out : ndarray, optional
    If provided, the destination to place the result. The shape must be
    correct, matching that of what stack would have returned if no
    out argument were specified.

Returns
-------
stacked : ndarray
    The stacked array has one more dimension than the input arrays.

See Also
--------
concatenate : Join a sequence of arrays along an existing axis.
block : Assemble an nd-array from nested lists of blocks.
split : Split array into a list of mul

In [2]:
import numpy as np
np.stack((arr1,arr2),axis=0)

NameError: name 'arr1' is not defined

In [290]:
np.stack((arr1,arr2),axis=1)

array([[2, 5],
       [3, 6],
       [6, 7]])

In [295]:
arr3 = np.stack((arr1,arr2),axis=1)

In [292]:
arr3

array([[2, 5],
       [3, 6],
       [6, 7]])

In [296]:
arr3[1][1]

6

In [163]:
arr3[1]

array([3, 6])

In [297]:
res = []
k = 0
for sub in arr3:
    res.append(sub[k])
res

[2, 3, 6]

In [166]:
#transpose of a matrix
arr3.T

array([[2, 3, 6],
       [5, 6, 7]])

In [300]:
arr4= np.array([[5,23,12],[90,23,1]])
arr4

array([[ 5, 23, 12],
       [90, 23,  1]])

In [301]:
np.sort(arr4)

array([[ 5, 12, 23],
       [ 1, 23, 90]])